---
version: '3'
dotenv: [.env]
tasks:
  hooks-init:
    desc: Initialize pre-commit
    cmds:
      - pre-commit install --hook-type pre-commit
      - pre-commit install --hook-type pre-push
      - pre-commit install --hook-type commit-msg
      - pre-commit autoupdate
  hooks-run:
    desc: Run pre-commit
    cmds:
      - |
        pre-commit run --show-diff-on-failure \
        --color always --all-files {{.CLI_ARGS}}
  prune:
    desc: Clean all the untracked files in the repository with some exceptions
    cmds:
      - task: clean
      - |
        git clean -f -xd --exclude=".idea" \
        --exclude=".env" --exclude="*.tfvars" \
        --exclude="backend.hcl" --exclude="backend.tf" \
        --exclude="Taskfile.yml"
